name: test
on: push

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: setup.py
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -e .[dev]
  pyright:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: jakebailey/pyright-action@v1
  ruff:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Lint
        run: ruff . --format github --respect-gitignore
  black:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: format
        run: black --check
